In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
diabetes_df=pd.read_csv('diabetes_with_names.csv')
diabetes_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0          6.0      148             72           35.0        0  33.6   
1          NaN       85             66           29.0        0  26.6   
2          8.0      183             64            0.0        0   NaN   
3          1.0       89             66           23.0       94  28.1   
4          0.0      137             40           35.0      168  43.1   

   DiabetesPedigreeFunction   Age  Outcome  
0                     0.627  50.0        1  
1                     0.351   NaN        0  
2                     0.672  32.0        1  
3                     0.167  21.0        0  
4                     2.288  33.0        1

In [3]:
diabetes_df.isna().sum()

Pregnancies                 2
Glucose                     0
BloodPressure               0
SkinThickness               1
Insulin                     0
BMI                         1
DiabetesPedigreeFunction    0
Age                         1
Outcome                     0
dtype: int64

In [5]:
diabetes_df=diabetes_df.fillna(diabetes_df.mean())
diabetes_df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
diabetes_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin        BMI  \
0     6.000000      148             72           35.0        0  33.600000   
1     3.849869       85             66           29.0        0  26.600000   
2     8.000000      183             64            0.0        0  32.003911   
3     1.000000       89             66           23.0       94  28.100000   
4     0.000000      137             40           35.0      168  43.100000   

   DiabetesPedigreeFunction        Age  Outcome  
0                     0.627  50.000000        1  
1                     0.351  33.243807        0  
2                     0.672  32.000000        1  
3                     0.167  21.000000        0  
4                     2.288  33.000000        1

In [7]:
X=diabetes_df.iloc[:,:-1]
y=diabetes_df.iloc[:,-1:]

In [8]:
X.head(1)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0          6.0      148             72           35.0        0  33.6   

   DiabetesPedigreeFunction   Age  
0                     0.627  50.0

In [9]:
y.head(1)

Outcome
0        1

In [10]:
from sklearn import model_selection 
X_train, X_test,y_train,y_test=model_selection.train_test_split(X, y, test_size=0.20, random_state=12)

In [11]:
X_train.shape

(614, 8)

In [12]:
diabetes_df.shape

(768, 9)

In [13]:
X_test.shape

(154, 8)

In [14]:
from sklearn import linear_model
logReg=linear_model.LogisticRegression()
logReg.fit(X_train,y_train)

C:\Users\DELL\AppData\Roaming\Python\Python37\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\DELL\AppData\Roaming\Python\Python37\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [15]:
y_pred=logReg.predict(X_test)
print(y_pred)

[0 1 1 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0 1 0 1 1 0 1 0 0 0
 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1
 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1
 0 1 0 1 0 0]


# Base Model Performance Evaluation

In [18]:
from sklearn import metrics
print('Accuracy Score \n',metrics.accuracy_score(y_test,y_pred))
print('\nConfusion Matrix\n',metrics.confusion_matrix(y_test,y_pred))
print('\nClassification report\n',metrics.classification_report(y_test,y_pred))

Accuracy Score 
 0.8116883116883117

Confusion Matrix
 [[91  8]
 [21 34]]

Classification report
               precision    recall  f1-score   support

           0       0.81      0.92      0.86        99
           1       0.81      0.62      0.70        55

    accuracy                           0.81       154
   macro avg       0.81      0.77      0.78       154
weighted avg       0.81      0.81      0.80       154



# Bagging Classifier

In [21]:
from sklearn import ensemble

bag_model=ensemble.BaggingClassifier(base_estimator=logReg,n_estimators=11,verbose=2)
bag_model.fit(X_train,y_train)
bag_pred=bag_model.predict(X_test)

print('Accuracy Score \n',metrics.accuracy_score(y_test,bag_pred))
print('\nConfusion Matrix\n',metrics.confusion_matrix(y_test,bag_pred))
print('\n Classification report\n',metrics.classification_report(y_test,bag_pred))

C:\Users\DELL\AppData\Roaming\Python\Python37\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
C:\Users\DELL\AppData\Roaming\Python\Python37\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\DELL\AppData\Roaming\Python\Python37\site-packages\sklearn\linear_model\_logistic.py:7

Building estimator 1 of 11 for this parallel run (total 11)...
Building estimator 2 of 11 for this parallel run (total 11)...
Building estimator 3 of 11 for this parallel run (total 11)...
Building estimator 4 of 11 for this parallel run (total 11)...
Building estimator 5 of 11 for this parallel run (total 11)...
Building estimator 6 of 11 for this parallel run (total 11)...
Building estimator 7 of 11 for this parallel run (total 11)...
Building estimator 8 of 11 for this parallel run (total 11)...
Building estimator 9 of 11 for this parallel run (total 11)...
Building estimator 10 of 11 for this parallel run (total 11)...
Building estimator 11 of 11 for this parallel run (total 11)...
Accuracy Score 
 0.8116883116883117

Confusion Matrix
 [[91  8]
 [21 34]]

 Classification report
               precision    recall  f1-score   support

           0       0.81      0.92      0.86        99
           1       0.81      0.62      0.70        55

    accuracy                           0.8

C:\Users\DELL\AppData\Roaming\Python\Python37\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\DELL\AppData\Roaming\Python\Python37\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modu

# Randomforest

In [22]:
rand_model=ensemble.RandomForestClassifier(n_estimators=10,verbose=0)
rand_model.fit(X_train,y_train)
rand_pred=rand_model.predict(X_test)

print('\nAccuracy Score \n',metrics.accuracy_score(y_test,rand_pred))
print('\nConfusion Matrix\n',metrics.confusion_matrix(y_test,rand_pred))
print('\nClassification report\n',metrics.classification_report(y_test,rand_pred))



Accuracy Score 
 0.7337662337662337

Confusion Matrix
 [[83 16]
 [25 30]]

Classification report
               precision    recall  f1-score   support

           0       0.77      0.84      0.80        99
           1       0.65      0.55      0.59        55

    accuracy                           0.73       154
   macro avg       0.71      0.69      0.70       154
weighted avg       0.73      0.73      0.73       154



C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  
