In [13]:
import numpy as np
from sklearn.metrics import confusion_matrix


In [17]:
real=np.random.randint(0,2,10)
calc=np.random.randint(0,2,10)

print(real,"\n",calc)

matrix1 = confusion_matrix(real,calc, labels=[1,0])
print("Confusion matrix : \n",matrix)

tp1, fn1, fp1, tn1 = confusion_matrix(real,calc, labels=[1,0]).reshape(-1)
print('Outcome values : \n', tp1, fn1, fp1, tn1)



[0 0 0 1 0 1 0 1 0 1] 
 [0 0 0 1 1 1 0 0 1 1]
Confusion matrix : 
 [[3 2]
 [2 3]]
Outcome values : 
 3 1 2 4


In [20]:
tp2, fn2, fp2, tn2 = (42,8,18,32)


precision = tp2 / (tp2 + fp2)
print(f"precision: {precision:4.2f}")
recall = tp2 / (tp2 + fn2)
print(f"recall: {recall:4.2f}")

f1_score = 2 * precision * recall / (precision + recall)


precision: 0.70
recall: 0.84


42